// Generated by CoffeeScript 2.3.1
(function() {
  var express, router, spawn, toolFactory;

  express = require('express');

  router = express.Router();

  ({spawn} = require('child_process'));

  router.get('/server-now', function(req, res, next) {
    return res.json({
      'server-datetime': new Date
    });
  });

  router.get('/client-browser-env', function(req, res, next) {
    return res.json({
      'req.headers': req.headers,
      'req.path': req.path,
      'req.params': req.params,
      'req.query': req.query
    });
  });

  router.get('/flushdb', function(req, res, next) {
    return res.send('i am ready to flush db.');
  });

  router.get('/savenow', function(req, res, next) {
    var savenow;
    // redis-cli is a link,live in "/usr/bin/"
    // ignores secure things,like authenticate and session,cookie
    savenow = spawn('redis-cli', ['save']);
    return savenow.on('close', function(code) {
      if ((parseInt(code)) !== 0) {
        return res.render('hasntsaved');
      } else {
        return res.render('hassaved');
      }
    });
  });

  // currism
  toolFactory = function(whichapp) {
    return function(whichpath) {
      return whichapp.use(whichpath, router);
    };
  };

  //module.exports = router
  module.exports = toolFactory;

}).call(this);
